name: map
description: A minimal Flutter ride booking and vector map demo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.27.1
  geolocator: ^14.1.1
  pointer_interceptor: ^0.10.1+3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  config:
    enable-windows-desktop: false
    enable-linux-desktop: false
    enable-macos-desktop: false
  uses-material-design: true
  licenses:
    - assets/fonts/OFL.txt
    - assets/map/LICENSE.md
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
  assets:
    - assets/map/
