"""Rebuild the research ledger from manually inspected primary-source evidence."""
from pathlib import Path
import hashlib
import json
from datetime import datetime, timezone

OUT = Path(__file__).resolve().parent
DATE = "2026-10-06"
STAMP = datetime.now(timezone.utc).isoformat()

def ident(value):
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:16]

rows = [
    ("Green SM", 2025, "Bảng giá dịch vụ Taxi Green SM tại TP. Hồ Chí Minh cập nhật", "https://www.greensm.com/vn-vi/news/bang-gia-xe-taxi-sai-gon", "Bảng giá, rows Car/Premium/Limo and note immediately below, web lines42–47", "Car: first2km30500 VND; next through12km15200/km; next through25km14700/km; after25km13300/km. Premium:34400/16500/16000/14400. Limo:39500/18900/18400/16500. Prices may change by time and promotion; app is reference for exact price.", "Historical publication2025-02-01, table observed2026-10-06; HCMC only, not national or live quote."),
    ("Be", 2023, "Thông báo về việc thay đổi tên gọi dịch vụ be Đi Tỉnh", "https://be.com.vn/tin-tuc/thong-bao-ve-viec-thay-doi-ten-goi-dich-vu-be-di-tinh/", "17/03/2023, paragraphs34–35", "The announced service covers long-distance trips of35km or more or interprovince/intercity trips; the old name was confusing for long trips within one province.", "Dated2023 statement; cannot infer all2026 dispatch or fare rules."),
    ("Be", 2021, "Tích hợp tính năng Đi Tỉnh theo lựa chọn điểm đến", "https://be.com.vn/tin-tuc/tich-hop-tinh-nang-di-tinh-theo-lua-chon-diem-den-thong-minh-va-tien-loi-hon/", "28/04/2021, lines32–44", "From29/04/2021 the normal booking flow automatically displays intercity or urban fares after pickup and destination are entered.", "Historical documented flow; offer details and app versions omitted."),
    ("Be", None, "Câu hỏi thường gặp", "https://be.com.vn/ho-tro/cau-hoi-thuong-gap/", "FAQ Đi tỉnh: lines139–165; changed destination lines57–64", "Intercity offers one-way and round-trip. Tolls, terminal, parking and other extra fees are excluded and discussed before departure. Final fare may change with actual waiting, distance and travel time. Drivers choose whether to accept or enable intercity requests.", "Undated FAQ includes historical content; not proof of current per-route availability, fixed wait rates or current cancellation policy."),
    ("Grab", 2026, "Bảng dịch vụ cập nhật Thuế suất VAT8%", "https://www.grab.com/vn/blog/driver/thongtindichvu/", "Published14/07/2026, GrabCar rows20–38", "GrabCar table separates minimum first2km, each subsequent km and travel-time after the first2km. Hanoi/HCMC GrabCar row28473 VND,9818/km,442/minute; tables vary by service and area.", "Published table observed06/10/2026. Quote may include demand/fees; rows are not a complete quote API."),
    ("Grab", 2025, "Cập nhật thông tin dịch vụ GrabCar2chiều", "https://www.grab.com/vn/en/blog/driver/grabcar2chieu/", "2026 updates; lines189–197 and231", "Round-trip4-hour or8-hour products include travel both directions and driver waiting. The final stop must be in the original pickup province/city; extra stops after starting are excluded. Displayed price excludes toll, airport, parking and other extras.", "Originally23/01/2025 but visibly updated2026. These products are not arbitrary one-way cross-country rides."),
    ("Green SM", 2026, "Green SM Liên Tỉnh", "https://www.greensm.com/vn-vi/green-lien-tinh", "Price policy lines35–51; booking lines168–190", "Policy26/08/2026 replaces previous policies. Lists named corridors, shared seats or privateLimo per-trip fares. Pickup/dropoff outside5km of nearest hub adds meter-rate distance beyond5km. Listed routes do not include HCMC–Hanoi.", "Negative claim limited to the displayed route list; not claim the company will never arrange a custom trip. Booking page gives conflicting15min vs1hour confirmation wording; no promise chosen."),
    ("Green SM", 2023, "Bảng giá xe taxi đường dài một số tuyến phổ biến", "https://www.greensm.com/vn-vi/news/taxi-duong-dai", "26/06/2023, city tables lines48–82", "Historical long-distance article publishes different Hanoi and HCMC tariffs, return discounts and waiting rates; round-trip return discount applies to the same passenger and pickup/final return in the same city.", "Historical only, supersession status not explicitly established. Do not use its numeric rates as current quote."),
    ("Grab", 2018, "Cách để thay đổi Điểm Đến trên hành trình đã đặt trước", "https://www.grab.com/vn/blog/changedestination/", "01/11/2018, lines10–24 and49–62", "Destination-change flow displays a new fare then requires confirmation. Article formula combines already-travelled distance, remaining distance to new destination, original surge and a change fee; it limits changes to once and excludes listed multi-stop/shared cases.", "Historical policy; article links to current-help fee details which were inaccessible via webopen, so no exact change fee is claimed."),
    ("Grab", 2026, "Bảng thông tin các dịch vụ trên ứng dụng Grab", "https://www.grab.com/vn/en/blog/bang-thong-tin-cac-dich-vu-tren-ung-dung-grab/", "Last update08/07/2026, paragraphs after full tables, indexed primary-source excerpt", "Public service information describes prices that can vary by regional/time supply and demand; surcharge categories include night, waiting beyond5minutes, destination changes and extra stops, plus platform/service charges. Scheduled cancellation is separately scoped.", "Page full-open long-output limits; relevant surcharge paragraph independently read in official indexed result. Do not copy scheduled fees into instant demo."),
    ("Be", 2019, "Giới thiệu dịch vụ gọi xe be Đi Tỉnh", "https://be.com.vn/be-news/gioi-thieu-dich-vu-goi-xe-be-di-tinh/", "16/12/2019, lines35–56", "The original service description covers trips from operating cities to nearby provinces, one-way or return. It historically describes included initial km/time and special overnight conditions rather than a single all-country flat formula.", "2019 introduction, not a current nationwide service-area or numeric fare promise."),
    ("Be", 2020, "Hướng dẫn be đi tỉnh – Dịch vụ Gọi xe đi tỉnh", "https://be.com.vn/be-rider-blog/bebike-becar-huong-dan-be-di-tinh-dich-vu-goi-xe-di-tinh/", "22/02/2020, lines40–61", "One-way fare adjustment is already applied by the app and must not be additionally collected by driver. Return waiting runs between end of outbound and start of return. Additional route distance and waiting are reflected in app total; discuss external fees before trip.", "2020 operating guidance; no attempt to assume present multipliers or waiting prices."),
    ("Grab", 2018, "BetterEveryday – Seamless Rides for Passengers", "https://www.grab.com/vn/better-everyday-2018/passenger/seamless-rides/", "Feature descriptions lines28–48", "Historical rider-flow article describes suggested pickup gates, new fare including distance already travelled after destination change, cancellation while searching without charge, and retrying another driver when first driver cancels.", "Historical feature description, not current cancellation price guarantee."),
    ("Grab", 2020, "GrabBike & GrabBike Premium – Thay Đổi Điểm Đón", "https://www.grab.com/vn/en/blog/driver/thay-doi-diem-don-2w/", "04/02/2020, THÔNG TIN CHUNG; official indexed text", "Pickup can be changed once after booking; excluded when multi-stop, new pickup too far or driver already near original pickup. This published policy is specifically for GrabBike/BikePremium.", "Historical Bike policy only. Exact allowed radius not available in source text and not invented for Car."),
]

sources, evidence, claims = [], [], []
display = {}
for number, (author, year, title, url, locator, summary, limitation) in enumerate(rows, 1):
    sid = ident(url.rstrip("/"))
    eid = ident(sid + summary)
    cid = ident(summary)
    display[sid] = number
    sources.append({"source_id": sid, "canonical_locator": url.rstrip("/"), "raw_url": url, "url": url, "title": title, "author": author, "year": year, "source_type": "official_company_policy", "retrieved_at": STAMP, "retrieved_date": DATE, "credibility_score": 90, "credibility_note": "Primary evidence for own published policy; not independent proof of service coverage or current proprietary pricing.", "limitations": limitation})
    evidence.append({"evidence_id": eid, "source_id": sid, "retrieval_query": url, "locator": locator, "quote": summary, "evidence_type": "paraphrase", "captured_at": STAMP})
    claims.append({"claim_id": cid, "text": summary, "claim": summary, "claim_type": "factual", "section_id": "main_analysis", "cited_source_ids": [sid], "source_ids": [sid], "evidence_ids": [eid], "support_status": "supported", "manual_support_status": "supported", "verification": "manual_meaning_check", "confidence": .92, "triangulation": "single_source_own_company_policy", "limitations": limitation})

for text, indexes in [
    ("Public policies distinguish operating area, product, direction, waiting and extra fees. Computing a route does not establish driver availability or a brand's binding quote.", [3, 5, 6]),
    ("For this educational demo, use configurable35km long-distance and300km or8hour special-trip thresholds; only35km has dated Be inspiration, none is universal current policy.", [1, 5, 6]),
    ("Demo uniform nationwide tier arithmetic uses the HCMC reference table as a named model version, not the actual national/live GreenSM product.", [0, 6, 7]),
    ("Demo changes before simulation should invalidate route and quote, recalculate, and require explicit reconfirmation; routing failures should block fare confirmation rather than fabricate road geometry.", [3, 8, 12]),
]:
    sids = [sources[i]["source_id"] for i in indexes]
    claims.append({"claim_id": ident(text), "text": text, "claim": text, "claim_type": "inference", "section_id": "recommendations", "cited_source_ids": sids, "source_ids": sids, "evidence_ids": [evidence[i]["evidence_id"] for i in indexes], "support_status": "supported_as_labeled_inference", "manual_support_status": "supported", "verification": "manual_meaning_check", "confidence": .9, "triangulation": "synthesis_across_brands" if indexes==[3,5,6] else "explicit_demo_design_proposal", "limitations": "Proposed implementation, not an asserted company policy or completed runtime QA."})

OUT.mkdir(parents=True, exist_ok=True)
for name, objects in [("sources.jsonl", sources), ("evidence.jsonl", evidence), ("claims.jsonl", claims)]:
    (OUT / name).write_text("".join(json.dumps(obj, ensure_ascii=False)+"\n" for obj in objects), encoding="utf-8")
(OUT / "display_numbers.json").write_text(json.dumps(display, ensure_ascii=False, indent=2), encoding="utf-8")
(OUT / "run_manifest.json").write_text(json.dumps({"query": "Nghiệp vụ khoảng cách/cước/đường dài/ngoại lệ Grab, Be, XanhSM cho bản demo map Flutter không xác thực", "mode": "quick_primary_policy_deep_dive", "date": DATE, "timezone": "Asia/Saigon", "source_count": len(sources), "assumptions": ["User asks nationwide educational simulation, not commercial dispatch.", "Published proprietary quotes cannot be reproduced from public static tables.", "Parent chooses unbranded demo reference tariff; thresholds are disclosed proposals."], "providers": {"search": "native Codex web", "domains": ["grab.com", "be.com.vn", "greensm.com"], "reference_ledgers": "local UTF-8 JSONL"}, "excluded": ["Unauthenticated third-party price comparisons", "Unavailable Grabhelp current fee numeric excerpt", "Claims of sub1metre guaranteed consumerGPS accuracy", "Claim live traffic/driver availability"], "coverage": ["Urban and longdistance", "Cross-country SG-Hanoi", "Vehicle types, tiers and price freshness", "Tolls/waiting/night/roundtrip", "Pickup and destination changes", "No-route and no-driver states"], "adaptation": "Current Green intercity corridor policy26/08/2026 replaced original emphasis on2023 taxi article; added explicit no-universal-price conclusion."}, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Saved {len(sources)} sources, {len(evidence)} evidence records, {len(claims)} claims")
